version: "3.1"

services:

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb_container
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - inception

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx_container
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress_container
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  db_volume:
    driver: local
    driver_opts:
      device: /home/jiyun/data/mariadb #makefile에서 만들어주고 지워주기
      type: none
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      device: /home/jiyun/data/wordpress
      type: none
      o: bind

networks:
    inception:
      driver: bridge

#로컬 드라이버는 호스트와 컨테이너 간의 파일 공유를 위해 사용되고,
#브리지 드라이버는 컨테이너 간의 네트워크 통신을 제공하기 위해 사용됩니다.
